server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codesec
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

codesec:
  crypto:
    master-key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="
  jwt:
    secret: "Y29kZVNlY1BsYXRmb3JtU2VjcmV0S2V5Rm9ySFMyNTY="
  engine:
    sandbox: false

logging:
  level:
    com.codesec: INFO
