cluster.name: codesec-cluster
node.name: codesec-es-node-1

network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

discovery.type: single-node

xpack.security.enabled: false

path.data: /usr/share/elasticsearch/data/data1,/usr/share/elasticsearch/data/data2,/usr/share/elasticsearch/data/data3
path.repo:
  - /usr/share/elasticsearch/backup

bootstrap.memory_lock: true

indices.query.bool.max_clause_count: 4096
indices.memory.index_buffer_size: 20%

thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000
